"""initial_schema

Revision ID: b569cd006c34
Revises: 
Create Date: 2026-10-03 15:36:01.199920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b569cd006c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Renumber any existing legacy run_events so unique constraint succeeds cleanly
    op.execute("""
        WITH numbered AS (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY run_id ORDER BY id ASC) as rn
            FROM run_events
        )
        UPDATE run_events
        SET sequence_number = numbered.rn
        FROM numbered
        WHERE run_events.id = numbered.id;
    """)
    op.create_index('idx_run_events_order_sequence', 'run_events', ['order_id', 'sequence_number'], unique=False)
    op.create_unique_constraint('uq_run_event_sequence', 'run_events', ['run_id', 'sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_run_event_sequence', 'run_events', type_='unique')
    op.drop_index('idx_run_events_order_sequence', table_name='run_events')
    # ### end Alembic commands ###
