"""initial_schema

Revision ID: b569cd006c34
Revises: 
Create Date: 2026-10-03 15:36:01.199920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b569cd006c34'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from app.database.base import Base
    import app.database.models  # ensure models are registered
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_run_event_sequence', 'run_events', type_='unique')
    op.drop_index('idx_run_events_order_sequence', table_name='run_events')
    # ### end Alembic commands ###
